# Generated by Django 5.1.5 on 2025-02-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldschema',
            name='is_required',
        ),
        migrations.AlterField(
            model_name='fieldschema',
            name='field_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fieldschema',
            name='is_unique',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fieldschema',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tableschema'),
        ),
    ]
