# Generated by Django 5.1.5 on 2025-02-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_fieldschema_is_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldschema',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
