# Generated by Django 5.1.5 on 2025-02-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fieldschema_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldschema',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fieldschema',
            unique_together={('table', 'name')},
        ),
    ]
